// Word list: English word + Hinglish/Hindi hint shown ONLY to the drawer.
// Guessers only see blanks for the English word — keep guessing language-neutral for now.
// Organize into packs so you can expand this later (school, festivals, family, bollywood, etc).

const WORDS = {
  everyday: [
    { word: "Apple", hint: "Seb" },
    { word: "Umbrella", hint: "Chhata" },
    { word: "Kite", hint: "Patang" },
    { word: "Bicycle", hint: "Cycle" },
    { word: "Slipper", hint: "Chappal" },
    { word: "Fan", hint: "Pankha" },
    { word: "Broom", hint: "Jhadu" },
    { word: "Bucket", hint: "Bucket/Balti" },
    { word: "Comb", hint: "Kangha" },
    { word: "Mirror", hint: "Aaina" },
    { word: "Key", hint: "Chaabi" },
    { word: "Lock", hint: "Taala" },
    { word: "Candle", hint: "Mombatti" },
    { word: "Matchbox", hint: "Maachis" },
    { word: "Newspaper", hint: "Akhbaar" },
    { word: "Clock", hint: "Ghadi" },
    { word: "Ladder", hint: "Seedi" },
    { word: "Basket", hint: "Tokri" },
    { word: "Blanket", hint: "Kambal" },
    { word: "Suitcase", hint: "Bag/Suitcase" },
  ],
  school: [
    { word: "Blackboard", hint: "Board" },
    { word: "Tiffin", hint: "Tiffin box" },
    { word: "Homework", hint: "Homework" },
    { word: "Uniform", hint: "School dress" },
    { word: "Pencil box", hint: "Pencil box" },
    { word: "Rickshaw", hint: "School rickshaw" },
    { word: "Exam", hint: "Pariksha" },
    { word: "Principal", hint: "Principal sir/madam" },
    { word: "Water bottle", hint: "Paani ki bottle" },
    { word: "Chalk", hint: "Chalk" },
    { word: "Timetable", hint: "Timetable" },
    { word: "Recess", hint: "Chutti ka time" },
    { word: "Notebook", hint: "Copy" },
    { word: "Eraser", hint: "Rubber" },
    { word: "School bag", hint: "Bastaa" },
    { word: "Assembly", hint: "Prarthana sabha" },
  ],
  family: [
    { word: "Grandmother", hint: "Dadi / Nani" },
    { word: "Uncle", hint: "Chacha / Mama" },
    { word: "Wedding", hint: "Shaadi" },
    { word: "Rickshaw driver", hint: "Rickshaw wala" },
    { word: "Sweets", hint: "Mithai" },
    { word: "Festival lights", hint: "Diwali lights" },
    { word: "Family dinner", hint: "Ghar ka khaana, sabke saath" },
    { word: "Elder's blessing", hint: "Aashirwad lena" },
    { word: "Family photo", hint: "Family photo" },
    { word: "Cousin", hint: "Cousin bhai/behen" },
    { word: "Grandfather's stories", hint: "Dada/Nana ki kahaniyan" },
    { word: "Family trip", hint: "Family trip" },
  ],
  bollywood: [
    { word: "Dance", hint: "Dance" },
    { word: "Villain", hint: "Villain" },
    { word: "Item song", hint: "Item song" },
    { word: "Interval", hint: "Interval" },
    { word: "Hero's entry", hint: "Hero ki entry" },
    { word: "Slow motion fight", hint: "Slow-motion fight scene" },
    { word: "Dramatic dialogue", hint: "Filmy dialogue" },
    { word: "Rain song", hint: "Baarish wala gaana" },
    { word: "Family drama", hint: "Family drama" },
    { word: "Comedy scene", hint: "Comedy scene" },
  ],
  animals: [
    { word: "Elephant", hint: "Hathi" },
    { word: "Peacock", hint: "Mor" },
    { word: "Monkey", hint: "Bandar" },
    { word: "Cow", hint: "Gaay" },
    { word: "Parrot", hint: "Tota" },
    { word: "Camel", hint: "Oont" },
    { word: "Buffalo", hint: "Bhains" },
    { word: "Street dog", hint: "Gali ka kutta" },
    { word: "Crow", hint: "Kauwa" },
    { word: "Snake", hint: "Saanp" },
    { word: "Tiger", hint: "Sher/Baagh" },
    { word: "Goat", hint: "Bakri" },
  ],
  festivals: [
    { word: "Diya", hint: "Diya" },
    { word: "Rangoli", hint: "Rangoli" },
    { word: "Firecrackers", hint: "Patakhe" },
    { word: "Holi colors", hint: "Holi ke rang" },
    { word: "Ganesh idol", hint: "Ganpati ki murti" },
    { word: "Eid moon", hint: "Eid ka chaand" },
    { word: "Christmas tree", hint: "Christmas tree" },
    { word: "Kite flying", hint: "Patang udaana" },
    { word: "Fireworks display", hint: "Aatishbaazi" },
    { word: "Puja thali", hint: "Puja ki thaali" },
  ],
  food: [
    { word: "Samosa", hint: "Samosa" },
    { word: "Chai", hint: "Chai" },
    { word: "Biryani", hint: "Biryani" },
    { word: "Golgappa", hint: "Golgappa / Pani puri" },
    { word: "Roti", hint: "Roti" },
    { word: "Mango", hint: "Aam" },
    { word: "Ice cream cone", hint: "Ice cream cone" },
    { word: "Pizza", hint: "Pizza" },
    { word: "Jalebi", hint: "Jalebi" },
    { word: "Coconut", hint: "Nariyal" },
    { word: "Vada pav", hint: "Vada pav" },
    { word: "Momo", hint: "Momo" },
  ],
  transport: [
    { word: "Auto rickshaw", hint: "Auto" },
    { word: "Local train", hint: "Local train" },
    { word: "Bullock cart", hint: "Bailgadi" },
    { word: "Scooter", hint: "Scooty" },
    { word: "Traffic jam", hint: "Traffic jam" },
    { word: "Metro", hint: "Metro" },
    { word: "Cricket stadium", hint: "Cricket stadium" },
    { word: "Airport", hint: "Airport" },
  ],
};

function getRandomWords(count = 3, packs = Object.keys(WORDS)) {
  const pool = packs.flatMap((p) => WORDS[p] || []);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

module.exports = { WORDS, getRandomWords };
